name: geo_env
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - numpy
  - geopandas
  - pandas
  - numpy
  - matplotlib
  - rasterio
  - rasterstats
  - statsmodels
  - scikit-learn
  - scipy
  - libpysal
  - tqdm
  - pip
  - geojson
  - descartes
  - folium
  - pysal
  - mapclassify
  - seaborn
  - geopy
  - tobler
  - osmnx
